# Generated by Django 4.2.11 on 2024-05-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(default='', max_length=255, verbose_name='Course type'),
        ),
        migrations.AddField(
            model_name='course',
            name='type_code',
            field=models.CharField(default='', max_length=255, verbose_name='Course type code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Course code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Course name'),
        ),
    ]
